# Generated by Django 5.2.5 on 2025-08-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='trade_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='trade_entry_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exit_price__isnull', True), ('exit_timestamp__isnull', True)), models.Q(('exit_price__isnull', False), ('exit_timestamp__isnull', False)), _connector='OR'), name='trade_exit_fields_both_or_neither'),
        ),
    ]
