# Generated by Django 5.2.5 on 2025-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_trade_exit_price_trade_exit_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trade',
            name='trade_exit_fields_both_or_neither',
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exit_price__isnull', True), ('exit_timestamp__isnull', True)), models.Q(('exit_price__isnull', False), ('exit_timestamp__isnull', False)), _connector='OR'), name='trade_exit_fields_both_or_neither'),
        ),
    ]
