# Generated by Django 5.2.5 on 2025-09-06 05:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_trade_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-entry_time']},
        ),
        migrations.RemoveConstraint(
            model_name='trade',
            name='trade_exit_fields_both_or_neither',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='exit_timestamp',
            new_name='exit_time',
        ),
        migrations.AddField(
            model_name='trade',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exit_price__isnull', True), ('exit_time__isnull', True)), models.Q(('exit_price__isnull', False), ('exit_time__isnull', False)), _connector='OR'), name='trade_exit_fields_both_or_neither'),
        ),
    ]
