# Generated by Django 5.2.5 on 2025-09-17 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_trade_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTradeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_side', models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('default_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
