# Generated by Django 5.2.5 on 2025-09-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_usertradesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradesettings',
            name='default_symbol',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
